apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trip
  template:
    metadata:
      labels:
        app: trip
        date: "{{ now | unixEpoch }}"
    spec:
      imagePullSecrets:
        - name: marshtravel-ghcr-registry
      containers:
        - name: auth
          image: ghcr.io/marshtravel/marshtravel-trip:lastest
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: '3003'
            - name: MONGODB_URI
              value: mongodb+srv://{{ .Values.mongodb.auth.username }}:{{ .Values.mongodb.auth.password }}@marshtravel.vv5rzyf.mongodb.net/?retryWrites=true&w=majority
            - name: RABBIT_MQ_URI
              value: amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@marshtravel-rabbitmq:5672
            - name: RABBIT_MQ_AUTH_QUEUE
              value: auth
            - name: RABBIT_MQ_DESTINATION_QUEUE
              value: destination
            - name: RABBIT_MQ_TRIP_QUEUE
              value: trip