apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        date: "{{ now | unixEpoch }}"
    spec:
      imagePullSecrets:
        - name: marshtravel-ghcr-registry
      containers:
        - name: auth
          image: ghcr.io/marshtravel/marshtravel-auth:lastest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: '3001'
            - name: MONGODB_URI
              value: mongodb+srv://{{ .Values.mongodb.auth.username }}:{{ .Values.mongodb.auth.password }}@marshtravel.vv5rzyf.mongodb.net/?retryWrites=true&w=majority
            - name: RABBIT_MQ_URI
              value: amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@marshtravel-rabbitmq:5672
            - name: RABBIT_MQ_AUTH_QUEUE
              value: auth
            - name: RABBIT_MQ_DESTINATION_QUEUE
              value: destination
            - name: RABBIT_MQ_TRIP_QUEUE
              value: trip
            - name: JWT_SECRET_KEY
              value: {{ .Values.jwtSecret.secretKey }}
            - name: JWT_REFRESH_KEY
              value: {{ .Values.jwtSecret.refreshKey }}
            - name: FIREBASE_SA
              value: {{ .Values.firebase.serviceAccount | toJson | quote }}
            - name: OAUTH2_CLIENT_ID_WEB
              value: {{ .Values.oauth2.clientIdWeb }}
            - name: OAUTH2_CLIENT_ID_ANDROID
              value: {{ .Values.oauth2.clientIdAndroid }}
            - name: OAUTH2_CLIENT_ID_IOS
              value: {{ .Values.oauth2.clientIdIos }}
            - name: GCLOUD_STORAGE_BUCKET_NAME
              value: {{ .Values.gcloud.storageBucketName }}
            - name: GCLOUD_SA
              value: {{ .Values.gcloud.serviceAccount | toJson | quote }}