apiVersion: apps/v1
kind: Deployment
metadata:
  name: destination
spec:
  replicas: 2
  selector:
    matchLabels:
      app: destination
  template:
    metadata:
      labels:
        app: destination
    spec:
      imagePullSecrets:
        - name: marshtravel-ghcr-registry
      containers:
        - name: auth
          image: ghcr.io/marshtravel/marshtravel-destination:lastest
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: '3002'
            - name: MONGODB_URI
              value: mongodb+srv://{{ .Values.mongodb.auth.username }}:{{ .Values.mongodb.auth.password }}@marshtravel.vv5rzyf.mongodb.net/?retryWrites=true&w=majority
            - name: RABBIT_MQ_URI
              value: amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@marshtravel-rabbitmq:5672
            - name: RABBIT_MQ_AUTH_QUEUE
              value: auth
            - name: RABBIT_MQ_DESTINATION_QUEUE
              value: destination
            - name: FIREBASE_SA
              value: {{ .Values.firebase.serviceAccount | toJson }}